- none-step/package.json
- none-step/vite.config.js
> 📝 :docs: package.json 추가

- none-step/src/components/location/LocationTracker.style.jsx
[merge/bomin] :lipstick:style: margin-top 제거
> [merge/bomin] :lipstick:style: margin-top 제거

- none-step/src/components/location/LocationTracker.style.jsx
- none-step/src/routes/AppRoutes.jsx
[merge/develop] :lipstick:style: margin-top 제거
> [merge/develop] :lipstick:style: margin-top 제거

- none-step/src/pages/MapPage/Map/Map.styles.jsx
- none-step/src/pages/MapPage/Map/StationInfo.styles.jsx
[merge/bomin] :lipstick:style: 지하철역 상세정보 스타일 수정
> [merge/bomin] :lipstick:style: 지하철역 상세정보 스타일 수정

- none-step/src/components/location/LocationTracker.style.jsx
- none-step/src/pages/MapPage/Map/Map.styles.jsx
- none-step/src/pages/MapPage/Map/StationInfo.styles.jsx
[merge/develop] :lipstick:style: 지하철역 상세정보 스타일 수정
> [merge/develop] :lipstick:style: 지하철역 상세정보 스타일 수정

- none-step/src/components/header/Headers.jsx
- none-step/src/components/location/LocationTracker.jsx
- none-step/src/components/location/LocationTracker.style.jsx
- none-step/src/components/menuBar/MenuBar.jsx
- none-step/src/pages/FindID/FindID.jsx
- none-step/src/pages/FindPW/FindPW.jsx
- none-step/src/pages/FindPW/FindPWResetting.jsx
- none-step/src/pages/FindWay/FindWay.jsx
- none-step/src/pages/FindWay/FindWay.style.jsx
- none-step/src/pages/FindWay/FindWayConfirm.jsx
- none-step/src/pages/FindWay/FindWayNav.jsx
- none-step/src/pages/FindWay/KakaoMapPlaceSearch.jsx
- none-step/src/pages/Login/Login.jsx
- none-step/src/pages/MyPage/MyPage.jsx
- none-step/src/pages/SignUp/SignUp01/TermsOfService.jsx
- none-step/src/pages/SignUp/SignUp02/SignUpForm.jsx
- none-step/src/routes/AppRoutes.jsx
1.  길찾기 중심좌표
- 지도 이동시 새로고침 되는 오류 수정
- 현재 위치 변경시 마커와 중심 좌표 함께 이동하도록 수정
2. 실시간 정차역 새로고침
- iOS 새로고침 업데이트 주기가 느린 문제 => watchPosition으로 사용자 위치 계속 추적하도록 수정
- 사용자의 편의에 따라 watchPosition 기능을 켜고 끌 수 있도록 토글 (watchPosition 사용시 배터리 소모 큼)
3. url 대문자 -> 소문자 수정
- AppRoutes 경로 수정 (오류 유발 가능성)
> [merge/develop] :bug:fix: 길찾기 중심좌표 오류 수정/ 실시간 정차역 새로고침 수정 / url 대문자 -> 소문자 수정

- none-step/src/components/header/Headers.jsx
- none-step/src/pages/ChattingPage/ChatCategory/BusanCategory.jsx
- none-step/src/pages/ChattingPage/ChatCategory/CapitalCategory.jsx
- none-step/src/pages/ChattingPage/ChatCategory/ChatCategory.styles.jsx
- none-step/src/pages/ChattingPage/ChatCategory/DaeguCategory.jsx
- none-step/src/pages/ChattingPage/ChatCategory/DaejeonCategory.jsx
- none-step/src/pages/ChattingPage/ChatCategory/GwangjuCategory.jsx
- none-step/src/pages/ChattingPage/ChatMenu/BusanChatMenu.jsx
- none-step/src/pages/ChattingPage/ChatMenu/CapitalChatMenu.jsx
- none-step/src/pages/ChattingPage/ChatMenu/DaeguChatMenu.jsx
- none-step/src/pages/ChattingPage/ChatMenu/DaejeonChatMenu.jsx
- none-step/src/pages/ChattingPage/ChatMenu/GwangjuChatMenu.jsx
- none-step/src/pages/ChattingPage/Chatting.jsx
- none-step/src/pages/ChattingPage/Chatting.styles.jsx
- none-step/src/pages/ChattingPage/ChattingMenu.jsx
- none-step/src/pages/ChattingPage/ChattingMenu.styles.jsx
- none-step/src/pages/ChattingPage/ChattingPage.jsx
- none-step/src/pages/MainPage/MainPage.jsx
- none-step/src/pages/MainPage/MainPage.styles.jsx
- none-step/src/pages/MapPage/Map/KakaoMap.jsx
- none-step/src/pages/MapPage/Map/Map.styles.jsx
- none-step/src/pages/MapPage/Map/StationInfo.jsx
- none-step/src/pages/MapPage/Map/StationInfo.styles.jsx
- none-step/src/routes/AppRoutes.jsx
- none-step/src/store/index.jsx
- none-step/src/store/rootReducer.jsx
- none-step/src/store/slices/categorySlice.jsx
[merge/bomin] ✨ feat: 채팅 메뉴 구현 / 채팅 입장 페이지 구현 / 메인 페이지 채팅 버튼 연결
> [merge/bomin] ✨ feat: 채팅 메뉴 구현 / 채팅 입장 페이지 구현 / 메인 페이지 채팅 버튼 연결

- none-step/src/components/menuBar/MenuBar.jsx
- none-step/src/routes/AppRoutes.jsx
[merge/bomin] :art:add: menuBar route 수정
> [merge/bomin] :art:add: menuBar route 수정

- none-step/src/components/menuBar/MenuBar.jsx
[merge/bomin] :art:add: menuBar 수정
> [merge/bomin] :art:add: menuBar 수정

- none-step/src/components/menuBar/MenuBar.jsx
- none-step/src/routes/AppRoutes.jsx
[merge/develop] :art:add: menuBar 수정
> [merge/develop] :art:add: menuBar 수정

- none-step/package.json
- none-step/src/components/menuBar/MenuBar.jsx
- none-step/src/layout/PrivateRoute.jsx
- none-step/src/pages/ChattingPage/ChatCategory/BusanCategory.jsx
- none-step/src/pages/ChattingPage/ChatCategory/CapitalCategory.jsx
- none-step/src/pages/ChattingPage/ChatCategory/DaeguCategory.jsx
- none-step/src/pages/ChattingPage/ChatCategory/DaejeonCategory.jsx
- none-step/src/pages/ChattingPage/ChatCategory/GwangjuCategory.jsx
- none-step/src/pages/ChattingPage/ChatMenu/BusanChatMenu.jsx
- none-step/src/pages/ChattingPage/ChatMenu/CapitalChatMenu.jsx
- none-step/src/pages/ChattingPage/ChatMenu/DaeguChatMenu.jsx
- none-step/src/pages/ChattingPage/ChatMenu/DaejeonChatMenu.jsx
- none-step/src/pages/ChattingPage/ChatMenu/GwangjuChatMenu.jsx
- none-step/src/pages/ChattingPage/Chatting.jsx
- none-step/src/pages/ChattingPage/Chatting.styles.jsx
- none-step/src/pages/ChattingPage/ChattingMenu.jsx
- none-step/src/pages/ChattingPage/ChattingMenu.styles.jsx
- none-step/src/pages/MainPage/MainPage.jsx
- none-step/src/routes/AppRoutes.jsx
- none-step/src/store/slices/categorySlice.jsx
[merge/bomin] ✨ feat: 지역별 노선별 실시간 채팅 구현
> [merge/bomin] ✨ feat: 지역별 노선별 실시간 채팅 구현

- none-step/src/pages/ChattingPage/Chatting.jsx
- none-step/src/pages/ChattingPage/Chatting.styles.jsx
[merge/bomin] :sparkles:feat: 채팅 날짜 구분선 구현
> [merge/bomin] :sparkles:feat: 채팅 날짜 구분선 구현

- none-step/src/pages/ChattingPage/Chatting.jsx
[merge/bomin] :bug:fix: 채팅 입장 시 스크롤 하단 이동 수정
> [merge/bomin] :bug:fix: 채팅 입장 시 스크롤 하단 이동 수정

- none-step/index.html
- none-step/public/nonestep.svg
[merge/bomin] :lipstick:style:favicon 변경
> [merge/bomin] :lipstick:style:favicon 변경

- none-step/index.html
- none-step/public/nonestep.svg
- none-step/src/pages/ChattingPage/Chatting.jsx
[merge/develop] :lipstick:style:favicon 변경
> [merge/develop] :lipstick:style:favicon 변경

- none-step/package.json
- none-step/src/pages/ChattingPage/Chatting.jsx
- none-step/src/pages/ChattingPage/Chatting.styles.jsx
- none-step/src/pages/MapPage/Map/KakaoMap.jsx
[merge/bomin] ✨feat: 채팅 가장 아래로 스크롤 되는 버튼 구현
> [merge/bomin] ✨feat: 채팅 가장 아래로 스크롤 되는 버튼 구현

- none-step/src/pages/ChattingPage/Chatting.jsx
[merge/bomin] :bug:fix: 채팅 삭제 후 복사하면 알림창 안 뜨는 오류 수정
> [merge/bomin] :bug:fix: 채팅 삭제 후 복사하면 알림창 안 뜨는 오류 수정

- none-step/src/pages/ChattingPage/Chatting.jsx
[merge/develop] :bug:fix: 네이버앱에서 채팅 보내지지 않는 오류 수정
> [merge/develop] :bug:fix: 네이버앱에서 채팅 보내지지 않는 오류 수정

- none-step/src/pages/ChattingPage/Chatting.jsx
[merge/bomin] :bug:fix: 네이버앱, 삼성브라우저 채팅 보내기 오류 수정
> [merge/bomin] :bug:fix: 네이버앱, 삼성브라우저 채팅 보내기 오류 수정

- none-step/src/pages/ChattingPage/Chatting.jsx
[merge/develop] :bug:fix: 네이버앱, 삼성브라우저 채팅 보내기 오류 수정
> [merge/develop] :bug:fix: 네이버앱, 삼성브라우저 채팅 보내기 오류 수정

- none-step/src/pages/ChattingPage/Chatting.jsx
- none-step/src/pages/ChattingPage/Chatting.styles.jsx
[merge/bomin] :bug:fix: 네이버앱, 삼성브라우저 채팅 보내기 오류 수정 3차
> [merge/bomin] :bug:fix: 네이버앱, 삼성브라우저 채팅 보내기 오류 수정 3차

- none-step/src/pages/ChattingPage/Chatting.jsx
- none-step/src/pages/ChattingPage/Chatting.styles.jsx
[merge/develop] :bug:fix: 네이버앱, 삼성브라우저 채팅 보내기 오류 수정 3차
> [merge/develop] :bug:fix: 네이버앱, 삼성브라우저 채팅 보내기 오류 수정 3차

- none-step/src/pages/ChattingPage/Chatting.jsx
[merge/bomin] :bug:fix: 네이버앱, 삼성브라우저 채팅 보내기 오류 수정 4차
> [merge/bomin] :bug:fix: 네이버앱, 삼성브라우저 채팅 보내기 오류 수정 4차

- none-step/src/pages/ChattingPage/Chatting.jsx
- none-step/src/pages/ChattingPage/Chatting.styles.jsx
[merge/develop] :bug:fix: 네이버앱, 삼성브라우저 채팅 보내기 오류 수정 4차
> [merge/develop] :bug:fix: 네이버앱, 삼성브라우저 채팅 보내기 오류 수정 4차

- none-step/index.html
- none-step/src/components/Button.jsx
- none-step/src/components/location/LocationTracker.style.jsx
- none-step/src/pages/MainPage/MainPage.jsx
- none-step/src/pages/MainPage/MainPage.styles.jsx
- none-step/src/pages/MyPage/MyPage.jsx
- none-step/src/pages/MyPage/MyPage.style.jsx
- none-step/src/styles/Theme.jsx
[merge/bomin] 💄 style: MyPage, LocationTracker 스타일 수정
> [merge/bomin] 💄 style: MyPage, LocationTracker 스타일 수정

- none-step/src/pages/MyPage/MyPage.jsx
- none-step/src/pages/MyPage/MyPage.style.jsx
[merge/bomin] :lipstick:style:MyPage 스타일 수정
> [merge/bomin] :lipstick:style:MyPage 스타일 수정

- none-step/package.json
- none-step/src/pages/MainPage/MainPage.jsx
- none-step/src/pages/MapPage/Map/KakaoMap.jsx
- none-step/src/pages/MapPage/Map/Map.styles.jsx
[merge/bomin] :art:add: axios update / 메인 페이지 컴포넌트 위치 변경 / 지도 radius 수정
> [merge/bomin] :art:add: axios update / 메인 페이지 컴포넌트 위치 변경 / 지도 radius 수정

- none-step/src/pages/MainPage/MainPage.styles.jsx
[merge/bomin] :art:add: 메인 페이지 편의시설 바로가기 가로 스크롤 스타일 수정
> [merge/bomin] :art:add: 메인 페이지 편의시설 바로가기 가로 스크롤 스타일 수정

- none-step/src/pages/MainPage/MainPage.styles.jsx
[merge/bomin] :art:add: 메인 페이지 편의시설 바로가기 아이콘 사이즈 수정
> [merge/bomin] :art:add: 메인 페이지 편의시설 바로가기 아이콘 사이즈 수정

- none-step/src/pages/ChattingPage/Chatting.jsx
- none-step/src/pages/ChattingPage/Chatting.styles.jsx
- none-step/src/routes/AppRoutes.jsx
[merge/bomin] :art:add: 비회원 채팅 조회 가능
> [merge/bomin] :art:add: 비회원 채팅 조회 가능

- none-step/src/pages/ChattingPage/Chatting.jsx
- none-step/src/pages/ChattingPage/Chatting.styles.jsx
- none-step/src/pages/MainPage/MainPage.styles.jsx
- none-step/src/routes/AppRoutes.jsx
[merge/develop] :art:add: 비회원 채팅 조회 가능
> [merge/develop] :art:add: 비회원 채팅 조회 가능

- none-step/src/pages/ChattingPage/Chatting.jsx
[merge/bomin] :art:add: 비회원 채팅 input 클릭 시 로그인 화면으로 이동
> [merge/bomin] :art:add: 비회원 채팅 input 클릭 시 로그인 화면으로 이동

- none-step/src/pages/ChattingPage/ChatMenu/BusanChatMenu.jsx
- none-step/src/pages/ChattingPage/ChatMenu/CapitalChatMenu.jsx
- none-step/src/pages/ChattingPage/ChatMenu/DaeguChatMenu.jsx
- none-step/src/pages/ChattingPage/ChatMenu/DaejeonChatMenu.jsx
- none-step/src/pages/ChattingPage/ChatMenu/GwangjuChatMenu.jsx
- none-step/src/pages/ChattingPage/Chatting.styles.jsx
- none-step/src/pages/ChattingPage/ChattingMenu.styles.jsx
- none-step/src/pages/MapPage/Map/KakaoMap.jsx
- none-step/src/pages/MapPage/Map/Map.styles.jsx
- none-step/src/pages/MapPage/Map/StationInfo.jsx
- none-step/src/pages/MapPage/Map/StationInfo.styles.jsx
[merge/bomin] ✨ feat: 채팅 목록 최근 채팅 시간 표시 / 지하철 역 기후 동행 카드 이용 가능 여부
> [merge/bomin] ✨ feat: 채팅 목록 최근 채팅 시간 표시 / 지하철 역 기후 동행 카드 이용 가능 여부

- none-step/src/pages/MapPage/Map/KakaoMap.jsx
- none-step/src/pages/MapPage/Map/StationInfo.jsx
- none-step/src/pages/MapPage/Map/StationInfo.styles.jsx
[merge/bomin] :sparkles:feat: 지하철 시간표 변경
> [merge/bomin] :sparkles:feat: 지하철 시간표 변경

- none-step/src/pages/MainPage/MainPage.jsx
[merge/bomin] :art:add: 메인페이지 편의시설 수정
> [merge/bomin] :art:add: 메인페이지 편의시설 수정

- none-step/src/pages/MapPage/Map/StationInfo.jsx
- none-step/src/pages/MapPage/Map/StationInfo.styles.jsx
- none-step/src/pages/MyPage/bookmark/BookmarkMap.jsx
- none-step/src/pages/MyPage/bookmark/BookmarkMap.styles.jsx
[merge/bomin] :sparkles:feat: 지하철 역 즐겨찾기 구현
> [merge/bomin] :sparkles:feat: 지하철 역 즐겨찾기 구현

- none-step/src/pages/MainPage/MainPage.jsx
- none-step/src/pages/MapPage/Map/StationInfo.jsx
- none-step/src/pages/MapPage/Map/StationInfo.styles.jsx
- none-step/src/pages/MyPage/bookmark/BookmarkMap.jsx
- none-step/src/pages/MyPage/bookmark/BookmarkMap.styles.jsx
[merge/develop] :sparkles:feat: 지하철 역 즐겨찾기 구현
> [merge/develop] :sparkles:feat: 지하철 역 즐겨찾기 구현

- none-step/src/pages/MapPage/Map/KakaoMap.jsx
- none-step/src/pages/MyPage/bookmark/BookmarkMap.jsx
- none-step/src/pages/MyPage/bookmark/BookmarkMap.styles.jsx
[merge/bomin] :sparkles:feat: 마이페이지 지도 즐겨찾기 클릭 시 지도 페이지 이동 구현
> [merge/bomin] :sparkles:feat: 마이페이지 지도 즐겨찾기 클릭 시 지도 페이지 이동 구현

- none-step/src/pages/ChattingPage/Chatting.styles.jsx
[merge/bomin] :art:add: 전체 채팅 메시지에 노선 표시 스타일 수정
> [merge/bomin] :art:add: 전체 채팅 메시지에 노선 표시 스타일 수정

- none-step/src/pages/MapPage/Map/KakaoMap.jsx
- none-step/src/pages/MapPage/Map/Map.styles.jsx
- none-step/src/pages/MapPage/Map/StationInfo.jsx
- none-step/src/pages/MapPage/Map/StationInfo.styles.jsx
[merge/bomin] :bug:fix: 지도 즐겨찾기에서 지도페이지 이동 시 상세정보 불러오기 실패 오류 해결
> [merge/bomin] :bug:fix: 지도 즐겨찾기에서 지도페이지 이동 시 상세정보 불러오기 실패 오류 해결

- none-step/src/pages/ChattingPage/Chatting.styles.jsx
- none-step/src/pages/MapPage/Map/KakaoMap.jsx
- none-step/src/pages/MapPage/Map/Map.styles.jsx
- none-step/src/pages/MapPage/Map/StationInfo.jsx
- none-step/src/pages/MapPage/Map/StationInfo.styles.jsx
[merge/develop] :bug:fix: 지도 즐겨찾기에서 지도페이지 이동 시 상세정보 불러오기 실패 오류 해결
> [merge/develop] :bug:fix: 지도 즐겨찾기에서 지도페이지 이동 시 상세정보 불러오기 실패 오류 해결

- none-step/src/pages/MapPage/Map/KakaoMap.jsx
[merge/bomin] :art:add: 지도 페이지 마커 크기 수정
> [merge/bomin] :art:add: 지도 페이지 마커 크기 수정

- none-step/src/pages/MapPage/Map/KakaoMap.jsx
[merge/develop] :art:add: 지도 페이지 위치 불러오기 코드 수정
> [merge/develop] :art:add: 지도 페이지 위치 불러오기 코드 수정

- none-step/src/pages/MapPage/Map/KakaoMap.jsx
[merge/bomin] :art:add: 지도 페이지 혼잡도 버튼 수정
> [merge/develop] :art:add: 지도 페이지 혼잡도 버튼 수정

- none-step/src/pages/MapPage/Map/StationInfo.jsx
[merge/bomin] :art:add: 역정보 상세정보 기후동행카드 수도권 외 지역 표시 오류 수정
> [merge/bomin] :art:add: 역정보 상세정보 기후동행카드 수도권 외 지역 표시 오류 수정

- none-step/src/pages/MapPage/Map/KakaoMap.jsx
- none-step/src/pages/MapPage/Map/StationInfo.jsx
[merge/develop] :art:add: 역정보 상세정보 기후동행카드 수도권 외 지역 표시 오류 수정
> [merge/develop] :art:add: 역정보 상세정보 기후동행카드 수도권 외 지역 표시 오류 수정

- none-step/src/pages/MyPage/bookmark/BookmarkMap.jsx
[merge/bomin] :art:add: 마이페이지 지도 즐겨찾기 역이름 표시 수정
> [merge/bomin] :art:add: 마이페이지 지도 즐겨찾기 역이름 표시 수정

- none-step/src/pages/MapPage/Map/StationInfo.jsx
- none-step/src/pages/MyPage/bookmark/BookmarkMap.jsx
[merge/develop] :art:add: 마이페이지 지도 즐겨찾기 역이름 표시 수정
> [merge/develop] :art:add: 마이페이지 지도 즐겨찾기 역이름 표시 수정

- none-step/src/components/header/Headers.jsx
- none-step/src/constants/license.js
- none-step/src/pages/LicensePage/LicensePage.jsx
- none-step/src/pages/LicensePage/LicensePage.styles.jsx
- none-step/src/pages/MainPage/MainPage.jsx
- none-step/src/pages/MainPage/MainPage.styles.jsx
- none-step/src/routes/AppRoutes.jsx
- none-step/vite.config.js
[merge/bomin] :sparkles:feat: 라이선스 페이지 구현
> [merge/bomin] :sparkles:feat: 라이선스 페이지 구현

- none-step/src/pages/MainPage/MainPage.jsx
[merge/bomin] :art:add: 메인페이지 지하철 혼잡도 수정
> [merge/bomin] :art:add: 메인페이지 지하철 혼잡도 수정

- none-step/src/constants/license.js
- none-step/src/pages/LicensePage/LicensePage.jsx
[merge/bomin] :art:add: 아이콘 라이선스 추가
> [merge/bomin] :art:add: 아이콘 라이선스 추가

- none-step/src/pages/MainPage/MainPage.jsx
- none-step/src/pages/MapPage/Congestion/CongestionDetailInfo.jsx
- none-step/src/pages/MapPage/Congestion/CongestionDetailInfo.styles.jsx
- none-step/src/pages/MapPage/Congestion/CongestionInfo.jsx
- none-step/src/pages/MapPage/Congestion/CongestionInfo.styles.jsx
- none-step/src/pages/MapPage/Congestion/CongestionTime.jsx
- none-step/src/pages/MapPage/Congestion/CongestionTime.styles.jsx
- none-step/src/pages/MapPage/Congestion/DistanceDetailInfo.jsx
- none-step/src/pages/MapPage/Congestion/DistanceDetailInfo.styles.jsx
- none-step/src/pages/MapPage/Map/KakaoMap.jsx
- none-step/src/pages/MapPage/Map/Map.styles.jsx
[merge/bomin] :sparkles:feat: 지도페이지 지하철혼잡도 구현
> [merge/bomin] :sparkles:feat: 지도페이지 지하철혼잡도 구현

- none-step/src/pages/MapPage/Congestion/CongestionInfo.styles.jsx
[merge/bomin] :art:add: 지하철혼잡도 상세정보 scroll 수정
> [merge/bomin] :art:add: 지하철혼잡도 상세정보 scroll 수정

- none-step/src/pages/MapPage/Congestion/CongestionInfo.jsx
[merge/bomin] :art:add: 지하철혼잡도 상세정보 방향 버튼 수정
> [merge/bomin] :art:add: 지하철혼잡도 상세정보 방향 버튼 수정

- none-step/src/pages/MapPage/Congestion/CongestionInfo.jsx
- none-step/src/pages/MapPage/Congestion/CongestionInfo.styles.jsx
[merge/develop] :art:add: 지하철혼잡도 상세정보 방향 버튼 수정
> [merge/develop] :art:add: 지하철혼잡도 상세정보 방향 버튼 수정

- none-step/src/pages/MapPage/Map/KakaoMap.jsx
[merge/bomin] :art:add: 지하철 혼잡도 마커 상, 하행선 방향 수정
> [merge/bomin] :art:add: 지하철 혼잡도 마커 상, 하행선 방향 수정

- none-step/src/pages/MapPage/Congestion/CongestionInfo.jsx
- none-step/src/pages/MapPage/Map/KakaoMap.jsx
[merge/develop] :art:add: 지하철 혼잡도 마커 상, 하행선 방향 수정
> [merge/develop] :art:add: 지하철 혼잡도 마커 상, 하행선 방향 수정

- none-step/src/pages/MapPage/Congestion/CongestionInfo.styles.jsx
[merge/bomin] :art:add: 지하철혼잡도 상세보기 높이 수정
> [merge/bomin] :art:add: 지하철혼잡도 상세보기 높이 수정

- none-step/src/pages/MapPage/Congestion/CongestionDetailInfo.jsx
- none-step/src/pages/MapPage/Congestion/CongestionInfo.jsx
- none-step/src/pages/MapPage/Congestion/CongestionInfo.styles.jsx
[merge/bomin] 🎨add: 지하철혼잡도 혼잡도에 따른 열차 색상 변경 및 지하철혼잡도 안내 문구 추가
> [merge/bomin] 🎨add: 지하철혼잡도 혼잡도에 따른 열차 색상 변경 및 지하철혼잡도 안내 문구 추가

- none-step/src/pages/MapPage/Congestion/CongestionInfo.jsx
- none-step/src/pages/MapPage/Congestion/CongestionInfo.styles.jsx
- none-step/src/pages/MapPage/Congestion/CongestionTime.jsx
[merge/bomin] :art:add: 지하철혼잡도 6호선 응암순환역 하행선만 표기
> [merge/bomin] :art:add: 지하철혼잡도 6호선 응암순환역 하행선만 표기

- none-step/src/pages/ChattingPage/Chatting.jsx
[merge/bomin] :art:add: 채팅 시간 표시 수정
> [merge/bomin] :art:add: 채팅 시간 표시 수정

- none-step/src/constants/license.js
- none-step/src/pages/LicensePage/LicensePage.jsx
- none-step/src/pages/LicensePage/LicensePage.styles.jsx
[merge/bomin] :art:add: 라이선스 페이지 파트별 구현
> [merge/bomin] :art:add: 라이선스 페이지 파트별 구현

- none-step/src/constants/license.js
- none-step/src/pages/ChattingPage/Chatting.jsx
- none-step/src/pages/LicensePage/LicensePage.jsx
- none-step/src/pages/LicensePage/LicensePage.styles.jsx
[merge/develop] :art:add: 라이선스 페이지 파트별 구현
> [merge/develop] :art:add: 라이선스 페이지 파트별 구현

- none-step/src/constants/license.js
[merge/bomin] :art:add: 라이선스 DATA 순서 정렬
> [merge/bomin] :art:add: 라이선스 DATA 순서 정렬

- none-step/src/constants/license.js
- none-step/src/pages/FindWay/FindWay.jsx
[merge/develop] :art:add: 라이선스 DATA 순서 정렬
> [merge/develop] :art:add: 라이선스 DATA 순서 정렬

- none-step/src/pages/NoticePage/NoticeList/NoticeList.jsx
[merge/bomin] :art:add: 공지사항 navigate 수정
> [merge/bomin] :art:add: 공지사항 navigate 수정

- none-step/src/constants/license.js
- none-step/src/pages/NoticePage/NoticeList/NoticeList.jsx
[merge/develop] :art:add: 공지사항 navigate 수정
> [merge/develop] :art:add: 공지사항 navigate 수정

- none-step/src/pages/MyPage/MyPage.jsx
- none-step/src/pages/MyPage/MyPage.style.jsx
[merge/bomin] :art:add: 프로필 사진 삭제 기능 추가
> [merge/bomin] :art:add: 프로필 사진 삭제 기능 추가

- none-step/src/pages/MainPage/MainPage.jsx
[merge/bomin] :art:add: 메인페이지 현재 위치 날씨 로딩 추가
> [merge/bomin] :art:add: 메인페이지 현재 위치 날씨 로딩 추가

- none-step/src/pages/FindWay/FindWay.jsx
[merge/bomin] :lipstick:style: 길찾기 지도 높이 수정
> [merge/bomin] :lipstick:style: 길찾기 지도 높이 수정

- none-step/src/pages/FindWay/FindWay.jsx
- none-step/src/pages/MainPage/MainPage.jsx
[merge/develop] :lipstick:style: 길찾기 지도 높이 수정
> [merge/develop] :lipstick:style: 길찾기 지도 높이 수정

- none-step/src/pages/FindWay/FindWay.jsx
- none-step/src/pages/FindWay/FindWay.style.jsx
- none-step/src/pages/FindWay/weather/Weather.style.jsx
[merge/bomin] :lipstick:style: 길찾기 컴포넌트 위치 수정
> [merge/bomin] :lipstick:style: 길찾기 컴포넌트 위치 수정

- none-step/src/pages/FindWay/FindWay.jsx
- none-step/src/pages/FindWay/FindWay.style.jsx
- none-step/src/pages/FindWay/weather/Weather.style.jsx
[merge/develop] :lipstick:style: 길찾기 컴포넌트 위치 수정
> [merge/develop] :lipstick:style: 길찾기 컴포넌트 위치 수정

- none-step/src/pages/MapPage/Congestion/CongestionInfo.jsx
- none-step/src/pages/MapPage/Map/KakaoMap.jsx
[merge/bomin] :sparkles:feat: 지하철 칸 혼잡도 구현
> [merge/bomin] :sparkles:feat: 지하철 칸 혼잡도 구현

- none-step/src/pages/MainPage/MainPage.jsx
- none-step/src/pages/MainPage/MainPage.styles.jsx
[merge/bomin] :art:add: 현재 위치 날씨에 현재 위치 주소 표시
> [merge/bomin] :art:add: 현재 위치 날씨에 현재 위치 주소 표시

- none-step/src/pages/MyPage/MyPage.jsx
- none-step/src/pages/MyPage/MyPage.style.jsx
- none-step/src/pages/MyPage/bookmark/BookmarkFindWay.jsx
- none-step/src/pages/MyPage/bookmark/BookmarkMap.jsx
- none-step/src/pages/MyPage/bookmark/BookmarkMap.styles.jsx
- none-step/src/pages/SignUp/SignUp02/SignUpForm.style.jsx
[merge/bomin] :art:add: 마이페이지 회원 탈퇴 문구 수정
> [merge/bomin] :art:add: 마이페이지 회원 탈퇴 문구 수정

- none-step/src/pages/FindWay/FindWay.jsx
- none-step/src/pages/FindWay/FindWay.style.jsx
- none-step/src/pages/FindWay/FindWayNav.jsx
- none-step/src/pages/FindWay/popup/FindWayPopup.jsx
- none-step/src/pages/FindWay/popup/FindWayPopup.style.jsx
- none-step/src/pages/FindWay/weather/Weather.jsx
- none-step/src/pages/FindWay/weather/Weather.style.jsx
[merge/bomin] :lipstick:style: 길찾기 페이지 위치 버튼 수정
> [merge/bomin] :lipstick:style: 길찾기 페이지 위치 버튼 수정
